#!/usr/bin/env python3
"""Extract grenade lineups from a practice workshop map into data/lineups/<map>.toml.

./extract_lineups.py <workshop id or .vpk> <map>    e.g. ./extract_lineups.py 3351615311 de_ancient

Works for maps built like the Astralis utility maps: a trigger_multiple at the stand position
turns on its target prop(s) and triggers a RELAY_<throw> hint, a playermodel prop marks the stand.
"""
import math, re, subprocess, sys, tempfile, tomllib
from pathlib import Path

from extract import CS2, ROOT, S2V

WORKSHOP = CS2.parent.parent / "workshop/content/730"
NADES = {"smoke": "smoke", "flashbang": "flash", "molotov": "molotov", "grenade_target": "molotov", "grenade": "he"}
EYE = 64  # pos is the standing eye position, like getpos


def s2v(*args):
    return subprocess.run([S2V, *args], check=True, capture_output=True, text=True).stdout


def entities(vpk):
    """entity dicts with their outputs as (output, input, target) in "@" """
    with tempfile.TemporaryDirectory() as tmp:
        inner = next(l.split()[0] for l in s2v("-i", vpk, "--vpk_list").splitlines() if re.match(r"maps/[^/]+\.vpk ", l))
        s2v("-i", vpk, "--vpk_filepath", inner, "-o", tmp)
        name = Path(inner).stem
        s2v("-i", Path(tmp) / inner, "--vpk_filepath", f"maps/{name}/entities/default_ents.vents_c", "-d", "-o", Path(tmp) / "ents")
        for block in re.split(r"^====\d+====$", (Path(tmp) / "ents").read_text(), flags=re.M):
            ent = {"@": []}
            for line in block.splitlines():
                k, _, v = line.partition(" ")
                if k.startswith("@"):
                    ent["@"].append((k[1:], *v.split(maxsplit=1)))
                elif k:
                    ent[k] = v.strip().strip('"')
            yield ent


def vec(s):
    return [float(x) for x in s.split()]


def floor(vpk, model, cache={}):
    """z of the model's feet relative to its origin"""
    if model not in cache:
        m = re.search(r"m_vMinBounds = \[ \S+ \S+ (\S+) \]", s2v("-i", vpk, "--vpk_filepath", model + "_c", "--all"))
        cache[model] = float(m.group(1))
    return cache[model]


def main(src, map_):
    vpk = Path(src) if src.endswith(".vpk") else WORKSHOP / src / f"{src}.vpk"
    ents = list(entities(vpk))
    props = [e for e in ents if e.get("classname") == "prop_dynamic"]
    stands = [e for e in props if "playermodel" in e.get("model", "")]
    spawns = {s: v["pos"] for s, v in tomllib.loads((ROOT / "data/spawns" / f"{map_}.toml").read_text()).items()}
    lines = [f"# generated by extract_lineups.py from {vpk.name}"]
    seen = set()
    for trig in ents:
        on = [t for o, i, t in trig["@"] if o == "OnStartTouch" and i in ("TurnOn", "Enable")]
        targets = [e for e in props if e.get("targetname") in on]
        if trig.get("classname") != "trigger_multiple" or not targets:
            continue
        name = re.sub(r"^\[.*?\]|_target$", "", targets[0]["targetname"])
        if name in seen:
            continue
        seen.add(name)
        x, y, z = vec(trig["origin"])
        stand = min(stands, key=lambda e: math.dist(vec(e["origin"])[:2], (x, y)))
        spawn = min(spawns, key=lambda s: math.dist(spawns[s][:2], (x, y)))
        model = targets[0]["model"]
        lines += ["", f"[{name}]"]
        if math.dist(vec(stand["origin"])[:2], (x, y)) < 48:
            x, y, z = vec(stand["origin"])
            z += floor(vpk, stand["model"]) + EYE
            model += stand["model"]
            if stand["model"].endswith("_c.vmdl"):
                lines.append("crouch = true")
            lines.append(f"pos = [{x:.2f}, {y:.2f}, {z:.2f}]")
        elif math.dist(spawns[spawn][:2], (x, y)) < 16:
            x, y, z = spawns[spawn]
            z += EYE
            lines.append(f'spawn = "{spawn}"')
        else:
            z += EYE - 45  # trigger centers sit about 45 above the floor
            lines.append(f"pos = [{x:.2f}, {y:.2f}, {z:.2f}]")
        help_ = [vec(t["origin"]) for t in targets]
        if lines[-1].startswith("pos"):  # look at the first target, spawns keep their angle
            dx, dy, dz = (a - b for a, b in zip(help_[0], (x, y, z)))
            lines.append(f"ang = [{-math.degrees(math.atan2(dz, math.hypot(dx, dy))):.2f}, {math.degrees(math.atan2(dy, dx)):.2f}, 0]")
        lines.append("help = [" + ", ".join("[" + ", ".join(f"{c:.2f}" for c in h) + "]" for h in help_) + "]")
        nade = next((v for k, v in NADES.items() if k in model), None)
        if nade:
            lines.append(f'nade = "{nade}"')
        throw = [t for o, i, t in trig["@"] if o == "OnStartTouch" and "RELAY_" in t]
        if throw:
            lines.append(f'throw = "{throw[0].split("RELAY_")[1].replace("_", " ")}"')
    out = ROOT / "data/lineups" / f"{map_}.toml"
    out.parent.mkdir(exist_ok=True)
    out.write_text("\n".join(lines) + "\n")
    print(f"{len(seen)} lineups -> {out}")


if __name__ == "__main__":
    sys.exit(main(*sys.argv[1:3]) if len(sys.argv) == 3 else __doc__)
