#!/usr/bin/env python3
"""Extract priority-0 spawns from CS2 map VPKs into data/spawns/<map>.toml."""
import os, re, subprocess, sys, tempfile
from pathlib import Path

ROOT = Path(__file__).parent
CS2 = Path(os.environ.get("CS2_DIR", Path.home() / ".local/share/Steam/steamapps/common/Counter-Strike Global Offensive"))
S2V = ROOT / ".tools/s2v/Source2Viewer-CLI"
SKIP = re.compile(r"_vanity$|^workshop_preview_|^lobby_|^graphics_settings$")
TEAMS = {"info_player_counterterrorist": "ct", "info_player_terrorist": "t"}


def entities(vpk, name):
    with tempfile.TemporaryDirectory() as tmp:
        out = Path(tmp) / "ents"
        subprocess.run([S2V, "-i", vpk, "--vpk_filepath", f"maps/{name}/entities/default_ents.vents_c", "-d", "-o", out],
                       check=True, capture_output=True)
        if not out.is_file():
            return
        for block in re.split(r"^====\d+====$", out.read_text(), flags=re.M):
            ent = {}
            for line in block.splitlines():
                k, _, v = line.partition(" ")
                ent[k] = v.strip().strip('"')
            yield ent


def vec(s):
    return [float(x) for x in re.split(r"[,\s]+", s.strip("[] \""))]


def main():
    for vpk in sorted((CS2 / "game/csgo/maps").glob("*.vpk")):
        name = vpk.stem
        if SKIP.search(name):
            continue
        spawns = {"ct": [], "t": []}
        for e in entities(vpk, name):
            team = TEAMS.get(e.get("classname"))
            if team and e.get("enabled", "true") == "true":
                spawns[team].append((int(e.get("priority", 0)), vec(e["origin"]), vec(e["angles"])))
        if not all(spawns.values()):
            continue
        lines = [f"# generated by extract.py from {vpk.name}"]
        for team, s in spawns.items():
            best = min(p for p, _, _ in s)
            for i, (_, pos, ang) in enumerate((x for x in s if x[0] == best), 1):
                lines += ["", f"[{team}_{i}]", f"pos = {pos}", f"ang = {ang}"]
        (ROOT / "data/spawns" / f"{name}.toml").write_text("\n".join(lines) + "\n")
        print(name, {t: sum(1 for x in s if x[0] == min(p for p, _, _ in s)) for t, s in spawns.items()})


if __name__ == "__main__":
    sys.exit(main())
