#!/usr/bin/env python3
"""Fetch all nades (no community ones) of the premier maps (csnades.gg's "Active Duty") into data/nades/<map>.toml.

./fetch_nades.py [map ...]    default: all active duty maps
"""
import json, re, sys, urllib.request
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

ROOT = Path(__file__).parent
SITE = "https://csnades.gg"
TYPES = {"smokes": "smoke", "molotovs": "molotov", "flashbangs": "flash", "hegrenades": "he"}  # url -> lineup nade
TECHNIQUE = {"left": "throw", "left_jump": "jumpthrow", "right": "right click", "right_jump": "right click jumpthrow",
             "both": "middle click", "both_jump": "middle click jumpthrow"}
MOVEMENT = {"stationary": "", "crouched_stationary": "crouch", "walking": "walk", "running": "run", "crouched_walking": "crouch walk"}


def get(path):
    req = urllib.request.Request(SITE + path, headers={"User-Agent": "kauz-tools-csgo (github.com/kauz56)"})
    with urllib.request.urlopen(req, timeout=30) as r:
        return r.read().decode()


def flight(html):
    """the React server payload of a page as one text"""
    return "".join(json.loads(m)[1] for m in re.findall(r"self\.__next_f\.push\((\[1,.*?\])\)</script>", html))


def objects(text, prefix):
    """all JSON objects in text starting with prefix"""
    dec = json.JSONDecoder()
    return [dec.raw_decode(text, m.start())[0] for m in re.finditer(re.escape(prefix), text)]


def active_duty():
    text = flight(get("/mirage"))  # map menu in the page payload
    return re.findall(r'"pathname":"/(\w+)"', text[text.index('"Active Duty"'):text.index('"Reserve"')])


def official(m, typ):
    nades = {n["slug"]: n for n in objects(flight(get(f"/{m}" + f"/{typ}" * (typ != "smokes"))), '{"id":"nade_')}
    def detail(n):
        page = flight(get(f"/{m}/{typ}/{n['slug']}"))
        d = next(d for d in objects(page, '{"uid":"nade_') if d["slug"] == n["slug"] and "console" in d)
        notes = [ln for ln in re.split(r"\n\n", d.get("videoVtt", ""))[1:] if ln.strip()]
        return n | {"console": d["console"], "notes": [" ".join(re.sub(r"<[^>]+>", "", ln.split("\n", 2)[-1]).split()) for ln in notes],
                    "url": f"{SITE}/{m}/{typ}/{n['slug']}"}
    with ThreadPoolExecutor(8) as ex:
        return list(ex.map(detail, nades.values()))


def lineup(n, nade):
    """csnades nade -> lineup table, None without a usable setpos/setang"""
    nums = re.fullmatch(r"\s*setpos\s+(\S+)\s+(\S+)\s+(\S+)\s*;\s*setang\s+(\S+)\s+(\S+)(?:\s+\S+)?\s*;?\s*", n.get("console") or "")
    if not nums:
        return None
    x, y, z, p, yaw = (float(v) for v in nums.groups())
    throw = " ".join(t for t in (MOVEMENT.get(n.get("movement"), ""), TECHNIQUE.get(n.get("technique"), "")) if t)
    out = {"title": f"{n['titleTo']} from {n['titleFrom']}", "pos": [x, y, z], "ang": [p, yaw, 0], "nade": nade, "throw": throw,
           "team": n.get("team", "any"), "precision": n.get("precision", ""), "url": n["url"]}
    if n.get("beginner"):  # the site's "recommended" filter
        out["recommended"] = True
    if n.get("notes"):
        out["notes"] = n["notes"]
    return out


def toml(v):
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, float):
        return f"{v:.10g}"
    if isinstance(v, list):
        return "[" + ", ".join(map(toml, v)) + "]"
    return json.dumps(v, ensure_ascii=False)  # a JSON string is a valid TOML basic string


def main(maps):
    out = ROOT / "data/nades"
    out.mkdir(parents=True, exist_ok=True)
    for m in maps:
        table, skipped = {}, 0
        for typ, nade in TYPES.items():
            for n in official(m, typ):
                if (lu := lineup(n, nade)) is None:
                    skipped += 1
                    continue
                key = n["slug"]
                if typ != "smokes":
                    key = f"{nade}-{key}"  # slugs are only unique per type
                table[key] = lu
        (out / f"de_{m}.toml").write_text(f"# generated by fetch_nades.py from {SITE}/{m}\n" + "".join(
            f"\n[{json.dumps(k)}]\n" + "".join(f"{f} = {toml(v)}\n" for f, v in lu.items()) for k, lu in sorted(table.items())))
        print(f"de_{m}: {len(table)} nades" + f", {skipped} without setpos skipped" * bool(skipped))


if __name__ == "__main__":
    main(sys.argv[1:] or active_duty())
