name: release
on:
  push:
    tags: ['v*']
permissions:
  contents: write
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: python3 gen.py --zip
      - run: gh release create "$GITHUB_REF_NAME" dist/kauz-tools-csgo.zip --generate-notes
        env:
          GH_TOKEN: ${{ github.token }}
